### ISSUE TITLE
Can this be used for signing older .NET Framework apps?

### ISSUE THREAD

**Issue by Rod-at-DOH** [Azure/azure-code-signing-action#13]
Looking at the example, it mentions setting up a .NET Core SDK. However, we have older, non-SDK style apps that need signing. Can this extension be used for those?

**Comment by japarson** [comment]
Hi @Rod-at-DOH, you can still sign non-SDK style apps with this Action. The Action itself requires .NET 6 to run, but there is no requirement for the app. As long as the build produces binaries that signtool can sign (e.g., exe, dll, etc.), you should have no issues. What's shown in the example is just a common use case.
