### ISSUE TITLE
Authenticating with Federated credentials

### ISSUE THREAD

**Issue by ldennington** [Azure/azure-code-signing-action#15]
Hello! Thanks for your awesome work on this action 🚀. I'm currently onboarding the [Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager) project to Azure Code Sign, and this is going to be super useful for us! However, we'd love to authenticate via Open ID Connect/Federated credentials (see description [here](https://docs.github.com/en/enterprise-server@3.8/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure)). Based on this [authentication description](https://github.com/marketplace/actions/azure-code-signing#authentication) and the [`DefaultAzureCredential` supported types](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet#definition), it seems like this type of authentication may not be availble with this action, but I wanted to double check with the experts to make sure 😊.

**Comment by japarson** [comment]
Hi Lessley, I'm seeing an example in the docs you linked on how an OIDC token can be used with the `azure\login` action to receive an Azure access token: https://docs.github.com/en/enterprise-server@3.8/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure#requesting-the-access-token

This would be compatible with `DefaultAzureCredential` via [`AzureCliCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azureclicredential?view=azure-dotnet).

Do you think this workflow would be suitable for your project? I'm not familiar with OIDC and I'm concerned about possibly misunderstanding the example.

**Comment by ldennington** [comment]
That worked! Thanks @japarson!
